Sync QE to CE.

diff --git a/install/plugins_makefile b/install/plugins_makefile
--- a/install/plugins_makefile
+++ b/install/plugins_makefile
@@ -8,14 +8,132 @@
 
 include ../make.sys
 include plugins_list
-PLUMED=PLUMED-latest
-GIPAW=qe-gipaw-latest
 #
 # MAIN target
 #
 
 EXTLIBS=liblapack libblas libiotk
 
+##########################################################
+# LD1
+###########################################################
+ld1:  uncompress-ld1
+	if test -d ../atomic; then \
+	cd ../atomic; $(MAKE) all; cd ../bin; ln -fs ../atomic/src/ld1.x . ; fi
+	touch make-ld1
+uncompress-ld1: touch-dummy
+	@(if test ! -e ../archive/$(LD1).tar.gz && test ! -d ../atomic ; then \
+	wget -O ../archive/$(LD1).tar.gz $(LD1_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	curl -o ../archive/$(LD1).tar.gz $(LD1_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	echo "unable to download ld1. Test whether curl or wget is installed in your computer." ; \
+	fi ; fi ; fi) 
+	if test ! -d ../atomic; then \
+	(gzip -dc ../archive/$(LD1).tar.gz | (cd ../ ; tar -xvf -)) ; fi
+	touch uncompress-ld1
+##########################################################
+# XSpectra
+###########################################################
+xspectra:  uncompress-xspectra
+	if test -d ../XSpectra; then \
+	cd ../XSpectra; $(MAKE) all; cd ../bin; ln -fs ../XSpectra/src/xspectra.x . ; fi
+	touch make-xspectra
+uncompress-xspectra: touch-dummy
+	@(if test ! -e ../archive/$(XSPECTRA).tar.gz && test ! -d ../XSpectra ; then \
+	wget -O ../archive/$(XSPECTRA).tar.gz $(XSPECTRA_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	curl -o ../archive/$(XSPECTRA).tar.gz $(XSPECTRA_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	echo "unable to download xspectra. Test whether curl or wget is installed in your computer." ; \
+	fi ; fi ; fi) 
+	if test ! -d ../XSpectra; then \
+	(gzip -dc ../archive/$(XSPECTRA).tar.gz | (cd ../ ; tar -xvf -)) ; fi
+	touch uncompress-xspectra
+##########################################################
+# PWCOND
+###########################################################
+pwcond:  uncompress-pwcond
+	if test -d ../PWCOND; then \
+	cd ../PWCOND; $(MAKE) all; cd ../bin; ln -fs ../PWCOND/src/pwcond.x . ; fi
+	touch make-pwcond
+uncompress-pwcond: touch-dummy
+	@(if test ! -e ../archive/$(PWCOND).tar.gz && test ! -d ../PWCOND ; then \
+	wget -O ../archive/$(PWCOND).tar.gz $(PWCOND_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	curl -o ../archive/$(PWCOND).tar.gz $(PWCOND_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	echo "unable to download pwcond. Test whether curl or wget is installed in your computer." ; \
+	fi ; fi ; fi) 
+	if test ! -d ../PWCOND; then \
+	(gzip -dc ../archive/$(PWCOND).tar.gz | (cd ../ ; tar -xvf -)) ; \
+	(cd ../ ; ln -s $(PWCOND) PWCOND) ; fi 
+	touch uncompress-pwcond
+##########################################################
+# NEB
+###########################################################
+neb:  uncompress-neb
+	if test -d ../NEB; then \
+	cd ../NEB; $(MAKE) all; cd ../bin; ln -fs ../NEB/src/neb.x . ; fi
+	touch make-neb
+uncompress-neb: touch-dummy
+	@(if test ! -e ../archive/$(NEB).tar.gz && test ! -d ../NEB ; then \
+	wget -O ../archive/$(NEB).tar.gz $(NEB_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	curl -o ../archive/$(NEB).tar.gz $(NEB_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	echo "unable to download neb. Test whether curl or wget is installed in your computer." ; \
+	fi ; fi ; fi) 
+	if test ! -d ../NEB; then \
+	(gzip -dc ../archive/$(NEB).tar.gz | (cd ../ ; tar -xvf -)) ; fi
+	touch uncompress-neb
+##########################################################
+# TDDFPT
+###########################################################
+tddfpt:  uncompress-tddfpt
+	if test -d ../TDDFPT; then \
+	cd ../TDDFPT; $(MAKE) all; cd ../bin; ln -fs ../TDDFPT/src/turbo_lanczos.x . ; \
+	ln -fs ../TDDFPT/tools/turbo_spectrum.x . ; fi
+	touch make-tddfpt
+uncompress-tddfpt: touch-dummy
+	@(if test ! -e ../archive/$(TDDFPT).tar.gz && test ! -d ../TDDFPT ; then \
+	wget -O ../archive/$(TDDFPT).tar.gz $(TDDFPT_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	curl -o ../archive/$(TDDFPT).tar.gz $(TDDFPT_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	echo "unable to download tddfpt. Test whether curl or wget is installed in your computer." ; \
+	fi ; fi ; fi) 
+	if test ! -d ../TDDFPT; then \
+	(gzip -dc ../archive/$(TDDFPT).tar.gz | (cd ../ ; tar -xvf -)) ; fi
+	touch uncompress-tddfpt
+##########################################################
+# PHonon
+###########################################################
+phonon:  uncompress-phonon
+	if test -d ../PHonon; then \
+	cd ../PHonon; $(MAKE) all; cd ../bin; \
+	ln -fs ../PHonon/PH/ph.x . ; \
+	ln -fs ../PHonon/PH/dynmat.x . ; \
+	ln -fs ../PHonon/PH/matdyn.x . ; \
+	ln -fs ../PHonon/PH/q2r.x . ; \
+	ln -fs ../PHonon/PH/q2qstar.x . ; \
+	ln -fs ../PHonon/PH/lambda.x . ; \
+	ln -fs ../PHonon/PH/fqha.x . ; \
+	ln -fs ../PHonon/Gamma/phcg.x . ; \
+	ln -fs ../PHonon/D3/d3.x . ; \
+	fi
+	touch make-phonon
+uncompress-phonon: touch-dummy
+	@(if test ! -e ../archive/$(PHONON).tar.gz && test ! -d ../PHonon ; then \
+	wget -O ../archive/$(PHONON).tar.gz $(PHONON_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	curl -o ../archive/$(PHONON).tar.gz $(PHONON_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	echo "unable to download phonon. Test whether curl or wget is installed in your computer." ; \
+	fi ; fi ; fi) 
+	if test ! -d ../PHonon; then \
+	(gzip -dc ../archive/$(PHONON).tar.gz | (cd ../ ; tar -xvf -)) ; fi
+	touch uncompress-phonon
 ##########################################################
 # GIPAW
 ###########################################################
@@ -24,16 +142,16 @@ gipaw:  uncompress-gipaw configure-gipaw
 	cd ../GIPAW; $(MAKE) all; cd ../bin; ln -fs ../GIPAW/bin/gipaw.x . ; fi
 	touch make-gipaw
 uncompress-gipaw: touch-dummy
-	@(if test ! -e ../archive/qe-gipaw-latest.tar.gz && test ! -d ../GIPAW ; then \
-	wget -O ../archive/qe-gipaw-latest.tar.gz http://qe-forge.org/frs/download.php/166/qe-gipaw-latest.tar.gz > /dev/null 2>&1; \
+	@(if test ! -e ../archive/$(GIPAW).tar.gz && test ! -d ../GIPAW ; then \
+	wget -O ../archive/$(GIPAW).tar.gz $(GIPAW_URL) > /dev/null 2>&1; \
 	if test "`echo $$?`" -ne "0" ; then \
-	curl -o ../archive/qe-gipaw-latest.tar.gz http://qe-forge.org/frs/download.php/166/qe-gipaw-latest.tar.gz > /dev/null 2>&1; \
+	curl -o ../archive/$(GIPAW).tar.gz $(GIPAW_URL) > /dev/null 2>&1; \
 	if test "`echo $$?`" -ne "0" ; then \
 	echo "unable to download qe-gipaw. Test whether curl or wget is installed in your computer." ; \
 	fi ; fi ; fi) 
 	if test ! -d ../GIPAW; then \
-	(gzip -dc ../archive/qe-gipaw-latest.tar.gz | (cd ../ ; tar -xvf -)) ; \
-	(cd ../ ; ln -s qe-gipaw* GIPAW) ; fi 
+	(gzip -dc ../archive/$(GIPAW).tar.gz | (cd ../ ; tar -xvf -)) ; \
+	(cd ../ ; ln -s $(GIPAW) GIPAW) ; fi 
 	touch uncompress-gipaw
 configure-gipaw: touch-dummy
 	cd ../GIPAW ; \
@@ -167,13 +285,21 @@ plumed: test-plumed uncompress-plumed patch-plumed
 	touch make-plumed
 test-plumed: touch-dummy
 	@(if test ! -e ../archive/$(PLUMED).tar.gz && test ! -d ../PLUMED; then \
-	echo "The release contains no PLUMED package"; fi) 
+	echo "The release contains no PLUMED package. Trying to download it from qe-forge."; fi) 
 	touch ./test-plumed
 uncompress-plumed: touch-dummy
-	if (test -e archive/$(PLUMED).tar.gz) || (test ! -d ../PLUMED); then \
-	( gzip -dc ../archive/$(PLUMED).tar.gz | (cd ../; tar -xvf -)) ; \
-	( mv ../PLUMED-latest ../PLUMED) ; fi
-	touch ./uncompress-plumed
+	@(if test ! -e ../archive/$(PLUMED).tar.gz && test ! -d ../PLUMED ; then \
+	wget -O ../archive/$(PLUMED).tar.gz $(PLUMED_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	curl -o ../archive/$(PLUMED).tar.gz $(PLUMED_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	echo "unable to download plumed. Test whether curl or wget is installed in your computer." ; \
+	fi ; fi ; fi) 
+	if test ! -d ../PLUMED; then \
+	(gzip -dc ../archive/$(PLUMED).tar.gz | (cd ../ ; tar -xvf -)) ; \
+	(cd ../ ; ln -s $(PLUMED) PLUMED) ; fi 
+	touch uncompress-yambo
+
 patch-plumed: touch-dummy
 	if test -d ../PLUMED; then \
 	(cd ../PLUMED ; export plumedir="`pwd`" ; \
@@ -182,23 +308,149 @@ patch-plumed: touch-dummy
 	touch ./patch-plumed
 
 ##################################
+# SaX
+##################################
+
+sax: extlibs uncompress-sax configure-sax
+	if test -d ../SaX; then \
+	cd ../SaX; $(MAKE) sax_all; fi
+#	- ( cd ../bin ; ln -sf ../SaX/sax/bin/* . ) 
+	touch ./make-want
+uncompress-sax: touch-dummy
+	@(if test ! -e ../archive/$(SAX).tar.gz && test ! -d ../SaX ; then \
+	wget -O ../archive/$(SAX).tar.gz $(SAX_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	curl -o ../archive/$(SAX).tar.gz $(SAX_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	echo "unable to download want. Test whether curl or wget is installed in your computer." ; \
+	fi ; fi ; fi) 
+	if test ! -d ../SaX; then \
+	(gzip -dc ../archive/$(SAX).tar.gz | (cd ../ ; tar -xvf -)) ; \
+	(cd ../ ; ln -s $(SAX) SaX) ; fi 
+	touch uncompress-sax
+
+configure-sax: touch-dummy
+	cd ../SaX ; \
+	./configure \
+	--with-external-iotk \
+	IOTK_LIBS="-L../../S3DE/iotk/src -liotk" \
+	IOTK_INCLUDE="$(MOD_FLAG)../../S3DE/iotk/src" \
+	CC="$(CC)" \
+	F90="$(F90)" \
+	MPIF90="$(MPIF90)" \
+	F90FLAGS="$(F90FLAGS) $($PRE_FDFLAGS) $(FDFLAGS) $(IFLAGS) $(MODFLAGS)" \
+	F77="$(F77)" \
+	FFLAGS="$(FFLAGS)" \
+	FFLAGS_NOOPT="$(FFLAGS_NOOPT)" \
+	LD="$(LD)" \
+	LDFLAGS="$(LDFLAGS)" \
+	AR="$(AR)" \
+	ARFLAGS="$(ARFLAGS)" \
+	RANLIB="$(RANLIB)" \
+	DFLAGS="$(DFLAGS)" \
+	FDFLAGS="$(DFLAGS)" \
+	LAPACK_LIBS="$(LAPACK_LIBS)" \
+	BLAS_LIBS="$(BLAS_LIBS)" \
+	FFT_LIBS="$(FFT_LIBS)" 
+	touch ./configure-sax
+
+
+##################################
 # extlibs
 ###################################
 extlibs:
 	test -n "$(EXTLIBS)" && ( cd .. ; $(MAKE) $(MFLAGS) $(EXTLIBS) || exit 1) || :
+
+##########################################################
+# GUI
+###########################################################
+gui:  uncompress-gui
+	touch make-gui
+uncompress-gui: touch-dummy
+	@(if test ! -e ../archive/$(GUI).tar.gz && test ! -d ../GUI ; then \
+	wget -O ../archive/$(GUI).tar.gz $(GUI_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	curl -o ../archive/$(GUI).tar.gz $(GUI_URL) > /dev/null 2>&1; \
+	if test "`echo $$?`" -ne "0" ; then \
+	echo "unable to download pwGUI. Test whether curl or wget is installed in your computer." ; \
+	fi ; fi ; fi) 
+	if test ! -d ../GUI; then \
+	(gzip -dc ../archive/$(GUI).tar.gz | (cd ../ ; tar -xvf -)) ; fi
+	touch uncompress-gui
+
 ###################################
 # cleaning
 ###################################
 # each lib independently
+ld1_clean:
+	if test -d ../atomic; then (cd ../atomic; \
+	$(MAKE) clean); fi
+	rm -f ../bin/ld1.x
+	rm -rf ./make-ld1 
+
+ld1_veryclean: ld1_clean
+# dir is not deleted for compatibility with the repository
+
+xspectra_clean:
+	if test -d ../XSpectra; then (cd ../XSpectra; \
+	$(MAKE) clean); fi
+	rm -f ../bin/xspectra.x
+	rm -rf ./make-xspectra
+
+xspectra_veryclean: xspectra_clean
+# dir is not deleted for compatibility with the repository
+
+pwcond_clean:
+	if test -d ../PWCOND; then (cd ../PWCOND; \
+	$(MAKE) clean); fi
+	rm -f ../bin/pwcond.x
+	rm -rf ./make-pwcond
+
+pwcond_veryclean: pwcond_clean
+# dir is not deleted for compatibility with the repository
+
+neb_clean:
+	if test -d ../NEB; then (cd ../NEB; \
+	$(MAKE) clean); fi
+	rm -f ../bin/neb.x
+	rm -rf ./make-neb 
+# dir is not deleted for compatibility with the repository
+
+tddfpt_clean:
+	if test -d ../TDDFPT; then (cd ../TDDFPT; \
+	$(MAKE) clean); fi
+	rm -f ../bin/turbo_lanczos.x
+	rm -f ../bin/turbo_spectrum.x
+	rm -rf ./make-tddfpt 
+# dir is not deleted for compatibility with the repository
+
+phonon_clean:
+	if test -d ../PHonon; then (cd ../PHonon; \
+	$(MAKE) clean); fi
+	rm -rf ../bin/ph.x
+	rm -rf ../bin/dynmat.x
+	rm -rf ../bin/matdyn.x
+	rm -rf ../bin/q2r.x
+	rm -rf ../bin/q2qstar.x
+	rm -rf ../bin/lambda.x
+	rm -rf ../bin/fqha.x
+	rm -rf ../bin/phcg.x
+	rm -rf ../bin/d3.x
+	rm -rf ./make-phonon 
+# dir is not deleted for compatibility with the repository
+# exe links to main bin dir are deleted by PHonon Makefile
+
 gipaw_clean:
 	if test -d ../GIPAW; then (cd ../GIPAW; \
 	$(MAKE) clean); fi
 	rm -f ../bin/gipaw.x
 	rm -rf ./make-gipaw 
+
 gipaw_veryclean: gipaw_clean
 	if test -d ../GIPAW; then (cd ../GIPAW; \
 	rm -f config.log config.status ); fi
 	rm -rf ./configure-gipaw
+
 epw_clean:
 	if test -d ../EPW; then (cd ../EPW; \
 	$(MAKE) clean); fi
@@ -215,7 +467,7 @@ w90_veryclean: w90_clean
 	if test -d ../W90; then (rm -R -f ../W90); fi
 	if test -d ../$(W90); then (rm -R -f ../$(W90)); fi
 	rm -f ../bin/wannier90.x
-	rm -rf ./make-w90 ./configure-w90 ./uncompress-w90
+	rm -rf ./uncompress-w90
 want_clean:
 	if test -d ../WANT; then (cd ../WANT; \
 	$(MAKE) clean); fi
@@ -224,7 +476,7 @@ want_clean:
 want_veryclean: want_clean
 	if test -d ../WANT; then (rm -R -f ../WANT); fi
 	if test -d ../$(WANT); then (rm -R -f ../$(WANT)); fi
-	- rm -rf ./make-want ./configure-want ./uncompress-want
+	- rm -rf ./uncompress-want
 yambo_clean:
 	if test -d ../YAMBO; then (cd ../YAMBO; \
 	$(MAKE) clean); fi
@@ -233,16 +485,35 @@ yambo_clean:
 yambo_veryclean: yambo_clean
 	if test -d ../YAMBO; then (rm -R -f ../YAMBO); fi
 	if test -d ../$(YAMBO); then (rm -R -f ../$(YAMBO)); fi
-	- rm -rf ./make-yambo ./configure-yambo ./uncompress-yambo
+	- rm -rf ./uncompress-yambo
+
 plumed_clean:
 	if test -d ../PLUMED; then (cd ../PLUMED; \
 	export plumedir="`pwd`" ; \
 	cd ../ ; ./plumedpatch_qespresso.sh -revert); fi
 	cd ../PW ; $(MAKE) clean; cd ../CPV ; $(MAKE) clean
 	rm -rf ./make-plumed ./patch-plumed
+
 plumed_veryclean: plumed_clean
 	if test -d ../PLUMED; then (rm -R -f ../PLUMED); fi
+	if test -d ../$(PLUMED); then (rm -R -f ../$(PLUMED)); fi
 	rm -rf ./uncompress-plumed ../plumedpatch_qespresso.sh
+
+sax_clean:
+	if test -d ../SaX; then (cd ../SaX; \
+	$(MAKE) clean); fi
+	- rm -rf ./make-sax ./configure-sax
+
+sax_veryclean: sax_clean
+	if test -d ../SaX; then (rm -R -f ../SaX); fi
+	if test -d ../$(SAX); then (rm -R -f ../$(SAX)); fi
+	- rm -rf ./uncompress-sax
+
+gui_clean:
+	rm -rf ./make-gui 
+
+gui_veryclean: gui_clean
+# dir is not deleted for compatibility with the repository
 
 ##########################################################
 # general cleaning
